jobs:
  test:
    name: Check Changelog presence
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: Graylog2/actions/changelog-check@main
name: Changelog Check
on:
  repository_dispatch:
    types: trigger-ga___changelog.yml
