concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  dispatchedMainBuild:
    name: Dispatch build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Debug event
      run: jq . "$GITHUB_EVENT_PATH"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GRAYLOG_PROJECT_INTERNAL_WORKFLOW_RW }}
      name: Dispatch build to graylog-project-internal
      run: 'gh workflow run -R Graylog2/graylog-project-internal main-build.yml --ref
        master -f caller_repo=${{ github.repository }} -f caller_branch=${{ github.base_ref
        || github.ref_name }} -f head_sha=${{ github.sha }} -f initial_actor="${{
        github.actor }}/${{ github.triggering_actor }}"

        '
name: Request a dispatched main branch build
on:
  repository_dispatch:
    types: trigger-ga___dispatch-main-build.yml
