concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  dispatchedPR:
    name: Dispatch wait and check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        NEW_PR_BODY: ${{ github.event.pull_request.body }}
        OLD_PR_BODY: ${{ github.event.changes.body.from }}
      id: pr-string-changed
      if: ${{ github.event.action == 'edited' }}
      name: Check if PR edit changed deps string
      run: "old_pr_string=$(grep -P '^/(jenkins-pr-deps|jpd|prd)' <<< \"$OLD_PR_BODY\"\
        \ | \\\n  grep -ioP '(Graylog2/\\S+?#|https?://github.com/Graylog2/\\S+?/pull/)[0-9]+'\
        \ || true)\nnew_pr_string=$(grep -P '^/(jenkins-pr-deps|jpd|prd)' <<< \"$NEW_PR_BODY\"\
        \ | \\\n  grep -ioP '(Graylog2/\\S+?#|https?://github.com/Graylog2/\\S+?/pull/)[0-9]+'\
        \ || true)\nif [ \"$old_pr_string\" != \"$new_pr_string\" ]; then\n  echo\
        \ \"PR deps string change detected: \\\"$old_pr_string\\\" -> \\\"$new_pr_string\\\
        \"\"\n  echo \"Re-triggering PR build...\"\n  exit 0\nfi\nexit 1\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GRAYLOG_PROJECT_INTERNAL_WORKFLOW_RW }}
      if: ${{ github.event.action != 'edited' || steps.pr-string-changed.outcome ==
        'success' }}
      name: Dispatch job to graylog-project-internal
      run: 'gh workflow run -R Graylog2/graylog-project-internal pr-build.yml --ref
        master -f caller_repo=${{ github.repository }} -f caller_pr_nr=${{ github.event.number
        }} -f caller_base_branch=${{ github.base_ref || github.ref_name }} -f caller_head_branch=${{
        github.head_ref }} -f head_sha=${{ github.event.pull_request.head.sha }} -f
        initial_actor="${{ github.actor }}/${{ github.triggering_actor }}"

        '
    - continue-on-error: true
      name: Give dispatched build time to add its status
      run: sleep 20
name: Request dispatched PR Build
on:
  repository_dispatch:
    types: trigger-ga___dispatch-pr-build.yml
