jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Freeing up more disk space
      run: 'sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don''t
        need Android

        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don''t need
        .NET

        '
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      env:
        JAVA_OPTS: -Xmx6G
      name: Build with Maven
      run: ./mvnw -B --fail-fast -Pedantic -Dspotbugs.skip -Dmaven.wagon.http.retryHandler.class=standard
        -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -DskipTests compile
    - continue-on-error: true
      name: Resetting lockfile
      run: git checkout yarn.lock
      working-directory: graylog2-web-interface
    - continue-on-error: true
      name: Run lint --fix
      run: yarn lint --fix -o /tmp/report.json -f json
      working-directory: graylog2-web-interface
    - continue-on-error: true
      name: Run lint:styles --fix
      run: yarn lint:styles --fix -o /tmp/report-stylelint.json -f json
      working-directory: graylog2-web-interface
    - continue-on-error: true
      name: Submit Results
      run: '/bin/sh ../.github/scripts/web-code-quality.sh | curl -X POST -H ''Content-Type:
        application/json'' -d @- ${{ secrets.DEV_METRICS_URL }}

        '
      working-directory: graylog2-web-interface
    - continue-on-error: true
      id: pr-create
      name: Create/Update Pull Request
      uses: peter-evans/create-pull-request@b3a2c5d525a1eb75e75c781e45a1bf3bfc23bdc6
      with:
        author: Dr. Lint-a-lot <garybot2@graylog.com>
        body: This PR was created by a job that is running periodically to find and
          fix linter hints.
        branch: fix/linter-hints
        commit-message: Running lint --fix
        committer: Dr. Lint-a-lot <garybot2@graylog.com>
        delete-branch: true
        title: Fixing linter hints automatically
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      id: pr-infos
      if: ${{ steps.pr-create.outputs.pull-request-number && steps.pr-create.outputs.pull-request-operation
        != 'closed' }}
      name: Get headRef and SHA of PR
      run: 'HEADREF=$(gh pr view ${{ steps.pr-create.outputs.pull-request-number }}
        --json headRefName --template ''{{.headRefName}}'')

        echo "sha=$(git rev-parse origin/$HEADREF)" >> $GITHUB_OUTPUT

        echo "headref=$HEADREF" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GRAYLOG_PROJECT_INTERNAL_WORKFLOW_RW }}
      if: ${{ steps.pr-create.outputs.pull-request-number && steps.pr-create.outputs.pull-request-operation
        != 'closed' }}
      name: Request dispatched PR build
      run: 'gh workflow run -R Graylog2/graylog-project-internal pr-build.yml --ref
        master -f caller_repo=${{ github.repository }} -f caller_pr_nr=${{ steps.pr-create.outputs.pull-request-number
        }} -f caller_base_branch=master -f caller_head_branch=${{ steps.pr-infos.outputs.headref
        }} -f head_sha=${{ steps.pr-infos.outputs.sha }} -f initial_actor="Dr. Lint-a-lot"

        '
    strategy:
      matrix:
        java-version:
        - 17
name: Fix linter hints
on:
  repository_dispatch:
    types: trigger-ga___fix-linter-hints.yml
